version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  vault:
    image: vault
    environment:
      - SKIP_SETCAP=1
      - VAULT_DEV_ROOT_TOKEN_ID=8fb95528-57c6-422e-9722-d2147bcba8ed

  rabbitmq:
    image: rabbitmq:3-management-alpine
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  memcached:
    image: memcached

  auth_service:
    build: ./auth_service
    restart: on-failure
    depends_on:
      - mongo
    environment:
      VIRTUAL_HOST: auth.local
      MONGO_URL: mongodb://admin:admin@mongo:27017

  products_service:
    build: ./products_service
    depends_on:
      - rabbitmq
      - mongo
    restart: on-failure
    environment:
      VIRTUAL_HOST: products.local 
      MONGO_URL: mongodb://admin:admin@mongo:27017
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/


