version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  vault:
    image: vault
    environment:
      - SKIP_SETCAP=1
      - VAULT_DEV_ROOT_TOKEN_ID=8fb95528-57c6-422e-9722-d2147bcba8ed

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  products_service:
    build: ./products_service
    depends_on:
      - rabbitmq
      - mongo
    restart: on-failure
    environment: 
      MONGO_URL: mongodb://admin:admin@mongo:27017
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/