version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis
    restart: always

  auth:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    restart: on-failure
    depends_on:
      - postgres
      - redis
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
      REDIS_URL: "redis:6379"
      VIRTUAL_HOST: auth.local

  products:
    build:
      context: .
      dockerfile: products_service/Dockerfile
    depends_on:
      - mongo
    restart: on-failure
    environment:
      MONGO_URL: mongodb://admin:admin@mongo:27017
      AUTH_URL: http://auth:8081
      VIRTUAL_HOST: product.local



