
POST {{auth_host}}/public/sign_in
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

> {%
    client.global.set("auth_token", response.body.token);
    client.global.set("refresh_token", response.body.refresh_token);
    %}

###


POST {{auth_host}}/public/refresh
Content-Type: application/json

{
    "refresh_token": "{{refresh_token}}"
}

> {%
    client.global.set("auth_token", response.body.token);
    client.global.set("refresh_token", response.body.refresh_token);
%}

###

GET {{auth_host}}/public/verify
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{products_host}}/admin
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{products_host}}/admin/63fdc0b13f140c842423cad3
Accept: application/json
Authorization: Bearer {{auth_token}}

###


POST {{products_host}}/admin
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Product {{$random.alphabetic(10)}}",
  "description": "Product {{$random.alphabetic(10)}}",
  "prices": [{
    "currency": "EUR",
    "price": {{$randomInt}}
  }]
}

> {%
    client.global.set("productId", response.body.id);
%}

###


GET {{products_host}}/public
Accept: application/json

> {% client.global.set("productId", response.body[0].id); %}
###

GET {{products_host}}/public/{{productId}}
Accept: application/json

###

POST {{products_host}}/public/{{productId}}/review
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "rating": 5,
  "comment": "Testing review {{$random.alphabetic(1000)}}"
}

###

GET {{inventory_host}}/public/inventory/{{productId}}
Accept: application/json

###


POST {{inventory_host}}/internal/inventory/add
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "product_id": "{{productId}}",
  "amount": 17
}

###

POST {{inventory_host}}/internal/inventory/subtract
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "product_id": "{{productId}}",
  "amount": 1
}

###

POST {{inventory_host}}/internal/inventory/reserve
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "cart_id": "cartId",
  "product_id": "{{productId}}",
  "amount": 12
}

###
