apiVersion: v1
kind: Pod
metadata:
  name: echo-manual
  labels:
    app: echo-manual
    env: dev
spec:
  containers:
    - image: ealen/echo-server:latest
      name: echo-server
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: PORT
          value: "8080"
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: echo-manual

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localhost-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /echo
            pathType: Prefix
            backend:
              service:
                name: echo
                port:
                  number: 80
