kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mongodb.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi