apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-secret
type: Opaque
data:
  MONGO_ROOT_USERNAME: {{ .Values.auth.rootUsername }}
  MONGO_ROOT_PASSWORD: {{ .Values.auth.rootPassword }}
  MONGO_USERNAME: {{ .Values.auth.mongoUsername }}
  MONGO_PASSWORD: {{ .Values.auth.mongoPassword }}
  MONGO_USERS_LIST: {{ .Values.auth.usersList }}