kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "postgresql.fullname" . }}-pvc
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ include "postgresql.fullname" . }}-local-storage
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
