apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgresql.fullname" . }}-stateful-set
spec:
  serviceName: {{ include "postgresql.fullname" . }}-stateful-set
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgresql.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ include "postgresql.fullname" . }}
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.fullname" . }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: {{ include "postgresql.fullname" . }}-data
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
      volumes:
        - name: {{ include "postgresql.fullname" . }}-data
          persistentVolumeClaim:
            claimName: {{ include "postgresql.fullname" . }}-pvc