version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - "27017:27017"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis
    restart: always

  auth:
    build:
      context: ../
      dockerfile: ./auth_service/Dockerfile
    restart: on-failure
    depends_on:
      - postgres
      - redis
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
      REDIS_URL: "redis:6379"
    ports:
      - "8081:8081"
