apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth_service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth_service
  template:
    metadata:
      labels:
        app: auth_service
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/manoamaro/auth_service:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghcr.io