apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service-deployment
  labels:
    app: products_service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products_service
  template:
    metadata:
      labels:
        app: products_service
    spec:
      containers:
        - name: products-service
          image: ghcr.io/manoamaro/products_service:latest
          ports:
            - containerPort: 8080